config/routes.rb
Ratemycamp::Application.routes.draw do
 
  get "users/index"
  get "users/show"

  devise_for :users

  resources :reviews

  resources :campsites do
    resources :reviews
  end

  root "pages#home"
  get "about" => "pages#about"
  get "users" => "users#index", as: "users"
  get "users/:id" => "users#show", as: "user"

end

app/models/campsite.rb
class Campsite < ActiveRecord::Base	
	include PgSearch
	pg_search_scope :search_by_sitename, :against => [:sitename, :nearesttown], :using => {
                    :tsearch => {:prefix => true}
                  }
 	pg_search_scope :search_by_state, :against => :state

 	has_many :reviews

end
	

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :campsite
	belongs_to :user

	validates :user_id, :presence => true
	validates :campsite_id, :presence => true
	validates :rating, :presence => true
	validates :comments, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews

  validates :username, :presence => true, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/campsites_controller.rb
class CampsitesController < ApplicationController
  before_action :set_campsite, only: [:show, :edit, :update, :destroy]

  # GET /campsites
  # GET /campsites.json
  def index
    if params.has_key?(:namequery)
      @campsites = Campsite.search_by_sitename(params[:namequery]).paginate(:page => params[:page], :per_page => 30, :order => "sitename ASC")
    elsif params.has_key?(:statequery)
      @campsites = Campsite.search_by_state(params[:statequery]).paginate(:page => params[:page], :per_page => 30, :order => "sitename ASC")
    else
      @campsites = Campsite.paginate(:page => params[:page], :per_page => 30, :order => "sitename ASC")
    end
  end

  # GET /campsites/1
  # GET /campsites/1.json
  def show
  end

  # GET /campsites/new
  def new
    @campsite = Campsite.new
  end

  # GET /campsites/1/edit
  def edit
  end

  # POST /campsites
  # POST /campsites.json
  def create
    @campsite = Campsite.new(campsite_params)

    respond_to do |format|
      if @campsite.save
        format.html { redirect_to @campsite, notice: 'Campsite was successfully created.' }
        format.json { render action: 'show', status: :created, location: @campsite }
      else
        format.html { render action: 'new' }
        format.json { render json: @campsite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campsites/1
  # PATCH/PUT /campsites/1.json
  def update
    respond_to do |format|
      if @campsite.update(campsite_params)
        format.html { redirect_to @campsite, notice: 'Campsite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @campsite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campsites/1
  # DELETE /campsites/1.json
  def destroy
    @campsite.destroy
    respond_to do |format|
      format.html { redirect_to campsites_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campsite
      @campsite = Campsite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campsite_params
      params[:campsite]
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		@campsites = Campsite.all
		@recent_reviews = Review.find(:all, :order => "id desc", :limit => 3)
		@highest_rated_campsites = Campsite.find_by_sql "SELECT *
														                          FROM (
														                            SELECT distinct c.id
														                              , c.sitename
														                              , round(avg(r.rating), 2) as average  
														                            FROM campsites c
														                              , reviews r
														                            WHERE c.id = r.campsite_id
														                            GROUP BY c.id, c.sitename
														                            )x
														                          ORDER BY x.average DESC
														                          LIMIT 5"
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @campsite = Campsite.find(params[:campsite_id])
    @review = current_user.reviews.new(:campsite_id => params[:campsite_id])
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @campsite = Campsite.find(params[:campsite_id])
    @review = @campsite.reviews.build(review_params)
    if @review.save
      redirect_to campsite_path(@campsite), notice: 'Thank you for submitting a review!' , class: "alert-info"
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    if @review.update(review_params)
      redirect_to campsite(@campsite), notice: 'Review was successfully updated.'
    else
      render action: 'edit' 
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
      redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comments, :user_id, :campsite_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all(:order => "id ASC")
  end

  def show
  	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campsites_helper.rb
module CampsitesHelper
	def us_states
    [
    	['', ''],
      ['Alabama', 'Alabama'],
      ['Alaska', 'Alaska'],
      ['Arizona', 'Arizona'],
      ['Arkansas', 'Arkansas'],
      ['California', 'California'],
      ['Colorado', 'Colorado'],
      ['Connecticut', 'Connecticut'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'Illinois'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
	end

  def us_states_distinct
    Campsite.uniq.pluck(:state).sort
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/campsites/_form.html.erb
<% if current_user.try(:admin?) %>

<%= form_for(@campsite) do |f| %>
  <% if @campsite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@campsite.errors.count, "error") %> prohibited this campsite from being saved:</h2>

      <ul>
      <% @campsite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<% end %>

app/views/campsites/edit.html.erb
<h1>Editing campsite</h1>

<%= render 'form' %>

<%= link_to 'Show', @campsite %> |
<%= link_to 'Back', campsites_path %>

app/views/campsites/index.html.erb
<div class="container">

  <%= form_tag campsites_path, method: :get do %>
    <%= text_field_tag :namequery, params[:namequery], :class => "search-box" %>
    <%= submit_tag "Search by name", name: nil, :class => "btn btn-success" %>
    <%= link_to 'Clear', campsites_path, class: "btn btn-danger" %>
    <%= link_to_function "Back", "history.back()", class: "btn btn-warning" %>
  <% end %>

  <br>

  <div class="inner">
    <table class="table">
      <thead>
        <tr>
          <th>Campsite</th>
          <th>Nearest Town</th>
          <th>State</th>
          <th>Reviews</th>
          <th>Average Rating</th>
        </tr>
      </thead>
      <tbody>
        <% @campsites.each do |campsite| %>
          <tr>
            <td><%= link_to campsite.sitename, campsite %></td>
            <td><%= campsite.nearesttown %></td>
            <td><%= campsite.state %></td>
            <td>
              <% if campsite.reviews.count > 0 %>
                <%= link_to "Read #{campsite.reviews.count} Review(s)", campsite_path(campsite), class: "btn btn-success btn-xs" %>
              <% else %>
                <%= link_to "Be the first to review!", campsite %>
              <% end %>
            </td>
            <td><strong><%= number_with_precision(campsite.reviews.average(:rating), significant: true)%></strong></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= will_paginate @posts %>

  </div>
</div>

app/views/campsites/new.html.erb
<% if current_user.try(:admin?) %>

	<h1>New campsite</h1>

	<%= render 'form' %>

	<%= link_to 'Back', campsites_path %>

<% else %>

<div class="container center">
	<p class="light-text">Nothing to see here. Move along.</p>
</div>

<% end %>

app/views/campsites/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 left">
			<div class="inner">
				<h1><%= @campsite.sitename %></h1>
				<% if @campsite.reviews.count > 0 %>
					<p><strong>Average Rating: <%= number_with_precision(@campsite.reviews.average(:rating), significant: true)%></strong></p>
					<p><strong>Reviews: <%= @campsite.reviews.count %></strong></p>
				<% end %>
				<% if @campsite.nearesttown %>
					<% if @campsite.distancefromnearesttown %>  
						<p><strong>Located <%= @campsite.distancefromnearesttown %> miles from <%= @campsite.nearesttown %>, <%= @campsite.state %></strong></p>
					<% else %>
					<p><strong>Located nearest <%= @campsite.nearesttown %>, <%= @campsite.state %></strong></p>
					<% end %>
				<% end %>

				<% if @campsite.numberofsites %>
					<p><strong>Contains <%= @campsite.numberofsites %> campsites.</strong></p>
				<% end %>

				<% if @campsite.phone %>
					<p><strong>Phone: <%= @campsite.phone %></strong></p>
				<% end %>

				<% if @campsite.reviews.count > 0 %>
					<% if user_signed_in? %>
						<p><%= link_to "Write a Review", new_campsite_review_path(@campsite, :campsite_id => @campsite.id), class: "btn btn-success" %></p>
					<% else %>
						<p><%= link_to "Write a Review", new_user_session_path, class: "btn btn-success" %></p>
					<% end %>
				<% end %>

				</div>
				<% if @campsite.reviews.count > 0 %>
						<div class="campsite-show-reviews-scroll">
							<% @campsite.reviews.reverse.each do |review| %>
								<div class="inner">
									<br>
									<p><i><strong>"<%= review.comments %>"</strong></i></p>
									Campsite: <strong><%= link_to review.campsite.sitename, campsite_path(review.campsite.id)%></strong>
									<br>Rating: <%= review.rating %> out of 5
									<br>Submitted by <strong><%= link_to review.user.username, review.user %></strong> on <%= review.created_at.advance(:hours => -5).strftime("%A, %B %e, %l:%m %P EST") %><br>
								</div>
							<% end %>
						</div>
				<% end %>
				<% if @campsite.reviews.count == 0 %>
					<div class="inner">
						<br>
						<p>Have you been to <%= @campsite.sitename %>?</p>
						<p>Help us out and be the first to tell us how it was!</p>
						<% if user_signed_in? %>
							<p><%= link_to "Write a Review", new_campsite_review_path(@campsite, :campsite_id => @campsite.id), class: "btn btn-success" %></p>
						<% else %>
							<p><%= link_to "Write a Review", new_user_session_path, class: "btn btn-success" %></p>
						<% end %>
					</div>
				<% end %>
			</div>

		<div class="col-md-6 right">
			<br><p><%= link_to_function "Return to previous page", "history.back()", class: "btn btn-warning" %></p><br>
						
			<iframe
				width="550"
				height="450"
				frameborder="0" style="border:0"
				src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCJuN7LyRB9OXNIyUlsZUCJRDSqE1jzGQs
				&q=<%= @campsite.latitude %>, <%= @campsite.longitude %>">
			</iframe>
		</div>
	</div>

	<div class="row">
		<div class="col-md-6 left">

		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "RateYourCamp.com", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <% if current_user.try(:admin?) %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Admin</a>
              <ul class="dropdown-menu">
                <li><%= link_to "Campsites", campsites_path %></li>
                <li><%= link_to "Reviews", reviews_path %></li>
                <li><%= link_to "Users", users_path %></li>
              </ul>
          </li>
          <% end %>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "My Account", edit_user_registration_path %></li>  
          <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>

        <% else %>
          <li><%= link_to "About", about_path %></li>  
          <li><%= link_to "Sign In", new_user_session_path %></li> 
        <% end %>      
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RateYourCamp.com</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>

	<% if notice %>
		<div class="container center">
			<p class="alert alert-success"><%= notice %></p>
		</div>
	<% end %>

	<% if alert %>
		<div class="container center">
  		<p class="alert alert-success"><%= alert %></p>
  	</div>
  <% end %>	 

	<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<div class="container center" style="width: 80%;">
	<div class="inner">
		<br>
		<p><strong>Welcome to RateYourCamp.com.</strong></p>
		<p>This website is designed to help you find a great camping spots and keep you away from the not-so-great spots.</p>
		<p>If you have been camping recently, help make the site a greater resource by leaving a review for the campsite.</p>
		<p>If you have any questions, comments, or suggestions for site improvement, please contact me at ineedtosetupsomekindofemail@rateyourcamp.com</p>
	</div>
</div>

app/views/pages/home.html.erb
<div class="container center">
  <div class="row">
	  <div class="col-md-6">
	  	<div class="inner">
		  	<h1>Search campsites by name</h1>
				<%= form_tag campsites_path, method: :get do %>
			    <%= text_field_tag :namequery, params[:namequery], :class => "form-inline" %>
			    <%= submit_tag "Search", name: nil, :class => "btn btn-success" %>
				<% end %>

				<h1>Search campsites by state</h1>
				<%= form_tag campsites_path, method: :get do %>
			    <%= select_tag :statequery, options_for_select(us_states_distinct), :class => "form-inline" %>
			    <%= submit_tag "Search", name: nil, :class => "btn btn-success" %>
				<% end %>
				<br>
			</div>
			<div class="inner">
				<h1>Highest rated campsites</h1>
				<table align="center">
			    <thead>
			      <tr>
			        <th>Campsite</th>
			        <th>Average Rating</th>
			        <th>Reviews</th>
			      </tr>
			    </thead>
			    <tbody>
					<% @highest_rated_campsites.each do |campsite| %>
						<tr>
							<td><strong><%= link_to campsite.sitename, campsite_path(campsite.id) %></strong></td>
							<td><%= campsite.average %></td>
							<td><%= campsite.reviews.count %></td>
						</tr>
					<% end %>
					</tbody>
				</table>
			</div>
	  </div>
		<div class="col-md-6">
	  	<div class="inner">
		  	<h1>Recently submitted reviews</h1>
		  	<br>
				<% @recent_reviews.each do |review| %>
					<p><i><strong>"<%= review.comments %>"</strong></i></p>
					Campsite: <strong><%= link_to review.campsite.sitename, campsite_path(review.campsite.id)%></strong>
					<br>Rating: <%= review.rating %> out of 5
					<br>Submitted by <strong><%= link_to review.user.username, review.user %></strong> on <%= review.created_at.advance(:hours => -5).strftime("%A, %B %e, %l:%m %P EST") %><br><br><br>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/reviews/_form.html.erb
<%= form_for [@campsite, @review] do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, :value => current_user.id %>

  <%= f.hidden_field :campsite_id %>

  <div class="field">
    <%= f.label :rating, "Overall Rating" %>
    <%= f.select :rating, (1..5) %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments, cols: 100, rows: 8 %>
  </div><br>
  <div class="actions">
    <%= submit_tag "Submit Review", name: nil, :class => "btn btn-success" %>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to_function "Return to previous page", "history.back()", class: "btn btn-warning" %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<div class="container center" style="width: 50%;">

  <div class="reviews-index-scroll">
    <% @reviews.reverse.each do |review| %>
      <div class="inner">
        <br>
        <p><i><strong>"<%= review.comments %>"</strong></i></p>
        Campsite: <strong><%= link_to review.campsite.sitename, campsite_path(review.campsite.id)%></strong>
        <br>Rating: <%= review.rating %> out of 5
        <br>Submitted by <strong><%= link_to review.user.username, review.user %></strong> on <%= review.created_at.advance(:hours => -5).strftime("%A, %B %e, %l:%m %P EST") %><br>
        <br><% if current_user.try(:admin?) %>
              <%= link_to 'Delete Review', review_path(review), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
            <% end %>
      </div>
    <% end %>
  </div>
  <br>
</div>

app/views/reviews/new.html.erb
<div class="container center" style="width: 80%;">
	<div class="inner">
		<h1>Write a new review for <%= Campsite.find_by_id(params[:campsite_id]).sitename %></h1>

		<%= render 'form' %>

		<br>
		
	</div>
</div>

app/views/reviews/show.html.erb
<div class="container">

	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Submitted By:</strong>
	  <%= @review.user.username %>
	</p>

	<p>
	  <strong>Campsite:</strong>
	  <%= link_to @review.campsite.sitename, campsite_path(@review.campsite) %>
	</p>

	<p>
	  <strong>Rating:</strong>
	  <%= @review.rating %>
	</p>

	<p>
	  <strong>Comments:</strong>
	  <%= @review.comments %>
	</p>

	<%= link_to 'Edit', edit_review_path(@review) %> |
	<%= link_to 'Back', reviews_path %>

</div>

app/views/users/index.html.erb
<% if current_user.try(:admin?) %>
<div class="container">
  <div class="inner">

  	<h1>Users</h1>

    <table class="table">
      <thead>
        <tr>
          <th>Username</th>
          <th>Reviews Submitted</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= link_to user.username, user %></td>
            <td><%= user.reviews.count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<% end %>

app/views/users/show.html.erb
<div class="container center" style="width: 50%;">
	<div class="light-text">
		<h1><%= @user.username %></h1>
		<p><strong>Member since <%= @user.created_at.advance(:hours => -5).strftime("%A, %B %e, %Y") %></strong></p>
		<p><strong>
			<% if @user.reviews.count %>
				<% if @user.reviews.count == 1 %>
					1 review submitted
				<% else %>
					<%= @user.reviews.count %> reviews submitted
				<% end %>
			<% else %>
				This user has not submitted any reviews
			<% end %>
		</strong></p>
	</div>
	<div class="user-show-reviews-scroll">
		<% @user.reviews.each do |review| %>
			<div class="inner">
			<br>
				<p><i><strong>"<%= review.comments %>"</strong></i></p>
				Campsite: <strong><%= link_to review.campsite.sitename, campsite_path(review.campsite.id)%></strong>
				<br>Rating: <%= review.rating %> out of 5
				<br>Submitted by <strong><%= link_to review.user.username, review.user %></strong> on <%= review.created_at.advance(:hours => -5).strftime("%A, %B %e, %l:%m %P EST")%><br>
			</div>
			<% end %>
	</div>
</div>